name: ğŸš€ Despliegue AutomÃ¡tico

on:
  push:
    branches: [ main ]

jobs:
  docker:
    name: ğŸ³ Construir y Subir a Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Descargar CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ” Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ› ï¸ Construir Imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo-devops:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo-devops:${{ github.sha }} .

      - name: ğŸ“¤ Subir Imagen a Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo-devops:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo-devops:${{ github.sha }}

  deploy:
    name: â˜ï¸ Desplegar en Render.com
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: ğŸš€ Disparar Deploy en Render
        uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}